image: hentzegroup/dewseq_test:devel

stages:
    - build
    - test

cmdbuild:
    stage: build
    artifacts:
        name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
        untracked: true
        expire_in: 1 week
    script:
        - R CMD build .

crancheck:
    stage: test
    dependencies:
        - cmdbuild
    script:
        - R CMD check DEWSeq*.tar.gz

bioccheck:
    stage: test
    dependencies:
        - cmdbuild
    script:
        - R -e  "library(BiocCheck);
            checkRes <- BiocCheck(Sys.glob('DEWSeq*.tar.gz')[1]);
            error<-FALSE;
            if(length(checkRes[['error']])>0){
                error<-TRUE;
                message('____ ERORRS ____\n\n');
                message(paste(checkRes[['error']],collapse='\n\n'));
                message('\n\n');
            };
            if(length(checkRes[['warning']])>0){
                error<-TRUE;
                message('____ WARNINGS ____\n\n');
                message(paste(checkRes[['warning']],collapse='\n\n'));
                message('\n\n');
            };
            if(length(checkRes[['note']])>0){
                message('____ NOTES ____\n\n');
                message(paste(checkRes[['note']],collapse='\n\n'));
                message('\n\n');
            };
            if(error){
                stop('Fix the warnings/errors above!');
            }else{
                message('No errors found!\n\nDONE...\n');}"
