image: hentzegroup/dewseq_test:devel

test:
    script:
        - R CMD build .
        - R -e  "library(BiocCheck);
            checkRes <- BiocCheck(Sys.glob('DEWSeq*.tar.gz')[1]);
            error<-FALSE;
            if(length(checkRes[['error']])>0){
                error<-TRUE;
                message(paste(checkRes[['error']],collapse='\n\n'));
            };
            if(length(checkRes[['warning']])>0){
                error<-TRUE;
                message(paste(checkRes[['warning']],collapse='\n\n'));
            };
            if(length(checkRes[['note']])>0){
                message(paste(checkRes[['note']],collapse='\n\n'));
            };
            if(error){
                stop('Fix the warnings/errors above!');
            }else{
                message('No errors found\n');}"

